package com.springmvc.pojo;
// Generated 2016-9-18 16:47:25 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TClass generated by hbm2java
 */
@Entity
@Table(name = "t_class", catalog = "test")
public class TClass implements java.io.Serializable {

	private int classId;
	private String className;
	private Integer teacherId;

	public TClass() {
	}

	public TClass(int classId) {
		this.classId = classId;
	}

	public TClass(int classId, String className, Integer teacherId) {
		this.classId = classId;
		this.className = className;
		this.teacherId = teacherId;
	}

	@Id

	@Column(name = "class_id", unique = true, nullable = false)
	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	@Column(name = "class_name", length = 45)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "teacher_id")
	public Integer getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

}
