package com.springmvc.pojo;
// Generated 2016-9-18 16:47:25 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TScore generated by hbm2java
 */
@Entity
@Table(name = "t_score", catalog = "test")
public class TScore implements java.io.Serializable {

	private int scoreId;
	private String score;
	private String cource;

	public TScore() {
	}

	public TScore(int scoreId) {
		this.scoreId = scoreId;
	}

	public TScore(int scoreId, String score, String cource) {
		this.scoreId = scoreId;
		this.score = score;
		this.cource = cource;
	}

	@Id

	@Column(name = "score_id", unique = true, nullable = false)
	public int getScoreId() {
		return this.scoreId;
	}

	public void setScoreId(int scoreId) {
		this.scoreId = scoreId;
	}

	@Column(name = "score", length = 45)
	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	@Column(name = "cource", length = 45)
	public String getCource() {
		return this.cource;
	}

	public void setCource(String cource) {
		this.cource = cource;
	}

}
