package com.springmvc.pojo;
// Generated 2016-9-18 16:47:25 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TStudent generated by hbm2java
 */
@Entity
@Table(name = "t_student", catalog = "test")
public class TStudent implements java.io.Serializable {

	private int stuId;
	private String stuName;
	private String stuAge;
	private Integer classId = 1;

	public TStudent() {
	}

	public TStudent(int stuId) {
		this.stuId = stuId;
	}

	public TStudent(int stuId, String stuName, String stuAge, Integer classId) {
		this.stuId = stuId;
		this.stuName = stuName;
		this.stuAge = stuAge;
		this.classId = classId;
	}

	@Id

	@Column(name = "stu_id", unique = true, nullable = false)
	public int getStuId() {
		return this.stuId;
	}

	public void setStuId(int stuId) {
		this.stuId = stuId;
	}

	@Column(name = "stu_name", length = 45)
	public String getStuName() {
		return this.stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

	@Column(name = "stu_age", length = 45)
	public String getStuAge() {
		return this.stuAge;
	}

	public void setStuAge(String stuAge) {
		this.stuAge = stuAge;
	}

	@Column(name = "class_id")
	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

}
