package com.springmvc.pojo;
// Generated 2016-9-18 16:47:25 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TTeacher generated by hbm2java
 */
@Entity
@Table(name = "t_teacher", catalog = "test")
public class TTeacher implements java.io.Serializable {

	private int teacherId;
	private String teacherName;

	public TTeacher() {
	}

	public TTeacher(int teacherId) {
		this.teacherId = teacherId;
	}

	public TTeacher(int teacherId, String teacherName) {
		this.teacherId = teacherId;
		this.teacherName = teacherName;
	}

	@Id

	@Column(name = "teacher_id", unique = true, nullable = false)
	public int getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}

	@Column(name = "teacher_name", length = 45)
	public String getTeacherName() {
		return this.teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

}
